const styles = {
  allowDownload: false,
  allowSocial: true,
  initialExpandedView: false,
  loveButton: true,
  isStoreGallery: false,
  loveCounter: false,
  allowTitle: true,
  allowTitleExpand: true,
  allowDescriptionExpand: true,
  allowLinkExpand: true,
  allowFullscreenExpand: true,
  allowExifExpand: false,
  defaultShowInfoExpand: true,
  showInfoExpandButton: false,
  expandInfoPosition: 'SIDE',
  addToCartButtonText: '',
  galleryAlignExpand: 'left',
  fullscreenLoop: false,
  mobileSwipeAnimation: 'EXPAND',
  actionsColorExpand: { themeName: 'color_17', value: 'rgba(226,197,161,1)' },
  bgColorExpand: { themeName: 'color_23', value: 'rgba(90,85,110,1)' },
  titleColorExpand: { themeName: 'color_15', value: 'rgba(0,0,0,1)' },
  descriptionColorExpand: { themeName: 'color_15', value: 'rgba(0,0,0,1)' },
  titleFontExpand: {
    style: { bold: true, italic: false, underline: false },
    family: 'open sans',
    preset: 'Page-title',
    editorKey: 'font_2',
    size: 17,
    fontStyleParam: true,
    displayName: 'Page Title',
    value: 'font:normal normal bold 17px/1.4em "open sans",sans-serif;',
  },
  descriptionFontExpand: {
    style: { bold: false, italic: false, underline: false },
    family: 'open sans',
    preset: 'Body-M',
    editorKey: 'font_8',
    size: 15,
    fontStyleParam: true,
    displayName: 'Paragraph 2',
    value: 'font:normal normal normal 15px/1.4em "open sans",sans-serif;',
  },
  sharpParams: { quality: 90, usm: {} },
  gotStyleParams: true,
  selectedLayout: 0,
  isRTL: false,
  isVertical: false,
  gallerySize: 1,
  minItemSize: 120,
  groupSize: 3,
  chooseBestGroup: true,
  groupTypes: '1,2h,2v,3t,3b,3l,3r',
  cubeImages: false,
  cubeType: 'fit',
  smartCrop: false,
  fullscreen: true,
  allowDescription: false,
  videoLoop: true,
  showVideoPlayButton: true,
  videoSound: false,
  videoSpeed: 1,
  videoPlay: 'onClick',
  gallerySliderImageRatio: 1.7777777777777777,
  galleryImageRatio: 2,
  numberOfImagesPerRow: 3,
  collageAmount: 0.8,
  collageDensity: 0.8,
  imageMargin: 74,
  galleryMargin: 0,
  floatingImages: 0,
  viewMode: 'preview',
  galleryHorizontalAlign: 'flex-start',
  galleryTextAlign: 'left',
  galleryVerticalAlign: 'flex-start',
  enableInfiniteScroll: true,
  itemClick: 'expand',
  cubeRatio: 1,
  fixedColumns: 0,
  oneRow: false,
  showArrows: true,
  isSlideshow: false,
  hasThumbnails: false,
  galleryThumbnailsAlignment: 'bottom',
  thumbnailSpacings: 0,
  gridStyle: 1,
  titlePlacement: 'SHOW_ON_HOVER',
  hoveringBehaviour: 'APPEARS',
  mobilePanorama: false,
  isAutoSlideshow: false,
  slideshowLoop: false,
  playButtonForAutoSlideShow: false,
  allowSlideshowCounter: false,
  autoSlideshowInterval: 4,
  arrowsSize: 23,
  slideshowInfoSize: 200,
  imageLoadingMode: 'BLUR',
  imageLoadingWithColorMode: 'PICKED_COLOR',
  imageRatioType: 'FIXED',
  numberOfDisplayedItems: 3,
  scrollAnimation: 'NO_EFFECT',
  overlayAnimation: 'NO_EFFECT',
  imageHoverAnimation: 'NO_EFFECT',
  expandAnimation: 'NO_EFFECT',
  itemBorderWidth: 0,
  itemBorderColor: { themeName: 'color_15', value: 'rgba(0,0,0,1)' },
  itemBorderRadius: 0,
  itemEnableShadow: false,
  itemShadowOpacityAndColor: {
    themeName: 'color_15',
    value: 'rgba(0,0,0,0.2)',
  },
  itemShadowBlur: 20,
  loadMoreAmount: 'all',
  itemShadowDirection: 135,
  itemShadowSize: 10,
  imageInfoType: 'NO_BACKGROUND',
  textBoxBorderRadius: 0,
  textBoxBorderWidth: 0,
  textBoxBorderColor: { themeName: 'color_15', value: 'rgba(0,0,0,1)' },
  titleDescriptionSpace: 6,
  textsVerticalPadding: 0,
  textsHorizontalPadding: 0,
  textBoxFillColor: { themeName: 'color_12', value: 'rgba(230,230,230,1)' },
  textBoxHeight: 0,
  textImageSpace: 10,
  alwaysShowHover: false,
  previewHover: false,
  calculateTextBoxHeightMode: 'MANUAL',
  scrollDirection: 0,
  galleryLayout: 0,
  thumbnailSize: 120,
  useCustomButton: false,
  customButtonText: '',
  itemOpacity: { themeName: 'color_14', value: 'rgba(155,155,155,0.6)' },
  itemFont: {
    style: { bold: false, italic: false, underline: false },
    family: 'open sans',
    preset: 'Heading-S',
    editorKey: 'font_6',
    size: 20,
    fontStyleParam: true,
    displayName: 'Small Heading',
    value: 'font:normal normal normal 20px/1.4em "open sans",sans-serif;',
  },
  itemFontSlideshow: {
    family: 'helvetica-w01-bold',
    displayName: 'Basic Heading',
    style: { bold: false, italic: false, underline: false },
    size: 22,
    preset: 'Custom',
    editorKey: 'font_5',
    fontStyleParam: true,
    value:
      'font:normal normal normal 22px/27px helvetica-w01-bold,helvetica-w02-bold,helvetica-lt-w10-bold,sans-serif;',
  },
  itemDescriptionFontSlideshow: {
    family: 'helvetica-w01-light',
    displayName: 'Paragraph 2',
    style: { bold: false, italic: false, underline: false },
    size: 15,
    preset: 'Custom',
    editorKey: 'font_8',
    fontStyleParam: true,
    value:
      'font:normal normal normal 15px/18px helvetica-w01-light,helvetica-w02-light,sans-serif;',
  },
  itemDescriptionFont: {
    family: 'open sans',
    style: { bold: false, italic: false, underline: false },
    size: 15,
    preset: 'Body-M',
    editorKey: 'font_8',
    fontStyleParam: true,
    displayName: 'Paragraph 2',
    value: 'font:normal normal normal 15px/1.4em "open sans",sans-serif;',
  },
  itemFontColor: { themeName: 'color_11', value: 'rgba(255,255,255,1)' },
  itemFontColorSlideshow: { themeName: 'color_15', value: 'rgba(0,0,0,1)' },
  itemDescriptionFontColor: {
    themeName: 'color_11',
    value: 'rgba(255,255,255,1)',
  },
  itemDescriptionFontColorSlideshow: {
    themeName: 'color_15',
    value: 'rgba(0,0,0,1)',
  },
  loadMoreButtonText: 'Load More',
  loadMoreButtonFont: {
    family: 'open sans',
    displayName: 'Paragraph 2',
    style: { bold: false, italic: false, underline: false },
    size: 15,
    preset: 'Body-M',
    editorKey: 'font_8',
    fontStyleParam: true,
    value: 'font:normal normal normal 15px/1.4em "open sans",sans-serif;',
  },
  loadMoreButtonFontColor: { themeName: 'color_15', value: 'rgba(0,0,0,1)' },
  loadMoreButtonColor: { themeName: 'color_11', value: 'rgba(255,255,255,1)' },
  loadMoreButtonBorderColor: { themeName: 'color_15', value: 'rgba(0,0,0,1)' },
  arrowsColor: { themeName: 'color_11', value: 'rgba(255,255,255,1)' },
  oneColorAnimationColor: {
    themeName: 'color_11',
    value: 'rgba(255,255,255,1)',
  },
  responsive: false,
  isAccessible: false,
  allowLeanGallery: false,
};

export { styles };
